name: Hexo Deploy
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Configuration environment
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
            mkdir -p ~/.ssh/
            echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "kaylor.chen@qq.com"
            git config --global user.name "kaylorchen"
            wget https://github.com/jgm/pandoc/releases/download/2.7/pandoc-2.7-1-amd64.deb
            sudo dpkg -i ./pandoc-2.7-1-amd64.deb
            npm install hexo-cli -g
            npm install hexo --save

      - name: Deploy hexo
        run: |
          node -v
          hexo clean
          hexo deploy

