name: Hexo process
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: Hexo
        run: |
          ls -al ./
          git config --global user.email "kaylor.chen@qq.com"
          git config --global user.name "kaylorchen"
          git config --global init.defaultBranch master
          git branch -v
          git checkout hexo
          sudo apt-get install -y nodejs
          npm install hexo
          npx hexo -v
          npx hexo g
          npx hexo d

