name: Hexo process
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: Hexo
        run: |
          ls -al ./
          curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install hexo
          npx hexo g
          npx hexo d

