name: Hexo process
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: Hexo
        run: |
          ls -al ./
          git config --global user.email "kaylor.chen@qq.com"
          git config --global user.name "kaylorchen"
          git config --global init.defaultBranch master
          curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs=12.21.0
          npm install hexo
          npx hexo -v
          npx hexo g
          npx hexo d

